    const_def
    const GETNAME_SOFTWARE
    const GETNAME_MOVE
    const GETNAME_PART
    const GETNAME_PARTYBOT
    const GETNAME_ITEM
    const GETNAME_PART_CLASS
    const GETNAME_SPECIES
    const GETNAME_WAREHOUSEBOT
