	const_def
	const D_RIGHT_F
	const D_LEFT_F
	const D_UP_F
	const D_DOWN_F
	const A_BUTTON_F
	const B_BUTTON_F
	const SELECT_F
	const START_F

DEF NO_INPUT   EQU %00000000
DEF D_RIGHT    EQU 1 << D_RIGHT_F
DEF D_LEFT     EQU 1 << D_LEFT_F
DEF D_UP       EQU 1 << D_UP_F
DEF D_DOWN     EQU 1 << D_DOWN_F
DEF A_BUTTON   EQU 1 << A_BUTTON_F
DEF B_BUTTON   EQU 1 << B_BUTTON_F
DEF SELECT     EQU 1 << SELECT_F
DEF START      EQU 1 << START_F

DEF BUTTONS    EQU A_BUTTON | B_BUTTON | SELECT | START
DEF D_PAD      EQU D_RIGHT | D_LEFT | D_UP | D_DOWN

DEF R_DPAD     EQU %00100000
DEF R_BUTTONS  EQU %00010000

DEF SCREEN_WIDTH EQU 20
DEF SCREEN_HEIGHT EQU 18
DEF SCREEN_WIDTH_PX EQU SCREEN_WIDTH * 8
DEF SCREEN_HEIGHT_PX EQU SCREEN_HEIGHT * 8
DEF BG_MAP_WIDTH EQU $20
DEF BG_MAP_HEIGHT EQU $20

	const_def
	const FACE_UP
	const FACE_RIGHT
	const FACE_DOWN
	const FACE_LEFT

DEF MEM_BLOCK_FREE EQU $55
DEF MEM_BLOCK_USED EQU $aa
