    const_def

    const PART_FISTARM
    const PART_FIST_2
    const PART_HAMMER
    const PART_HAMMER2
    const PART_SANBO_A
    const PART_BOXER_A
    const PART_KICKBOX
    const PART_WOLF_F
    const PART_TIGER_A
    const PART_FIGHT_H
    const PART_SPAZARM
    const PART_DAGGER
    const PART_SWORD_A
    const PART_SAMURAI
    const PART_KATANA
    const PART_TOMHAWK
    const PART_LEINT_H
    const PART_PICKARM
    const PART_SCIM_A
    const PART_SPEAR_A
    const PART_GRAVE_A
    const PART_VOIDHND
    const PART_HERBARM
    const PART_TAROT_A
    const PART_MITHRIL
    const PART_ANGEL_A
    const PART_BLESS_H
    const PART_EMPEROR
    const PART_LUNEARM
    const PART_SOLAR_A
    const PART_CLEAN_A
    const PART_JUDGE_H
    const PART_GAIAHND
    const PART_GUNHAND
    const PART_RIFLE_A
    const PART_SHOTGUN
    const PART_GATLING
    const PART_BALKN_A
    const PART_GRENADE
    const PART_BAZOK_A
    const PART_LASER_A
    const PART_MEGALSR
    const PART_BEAMARM
    const PART_HYPBEAM
    const PART_KNIFE_A
    const PART_SHARP_C
    const PART_DRGNCRW
    const PART_ROPEARM
    const PART_THRIL_H
    const PART_JET_ARM
    const PART_CHEAT_A
    const PART_SEEKARM
    const PART_THROWER
    const PART_HARDTHW
    const PART_CROSBOW
    const PART_TYREL_A
    const PART_CLAWARM
    const PART_MACEARM
    const PART_FLAIL_A
    const PART_GRAB_A
    const PART_BUSTER
    const PART_POWER_A
    const PART_BLADE_A
    const PART_CAVEARM
    const PART_KATOK_A
    const PART_PILEBNK
    const PART_HYPER_C
    const PART_CHARM_H
    const PART_NAGA_A
    const PART_DEATH_H
    const PART_BLOCK_H
    const PART_GULL_H
    const PART_BLOOD_H
    const PART_ASHUR_A
    const PART_OGREARN
    const PART_GEEK_H
    const PART_WISEARM
    const PART_SLEDGE
    const PART_BRENARM
    const PART_CHEMHND
    const PART_MAGIC_A
    const PART_BOLTS
    const PART_WIN_ARM
    const PART_SHELL_H
    const PART_6_WAY_A
    const PART_RESIST
    const PART_SERVE_H
    const PART_RATARM
    const PART_ORACLE
    const PART_PROPEL
    const PART_WING
    const PART_JET
    const PART_TURBO_J
    const PART_GLIDER
    const PART_BOOSTER
    const PART_KAMIKAZ
    const PART_8MMGUN
    const PART_SONIC
    const PART_SKYBOMB
    const PART_ATOMIC
    const PART_SCREW
    const PART_HOVER
    const PART_SONAR
    const PART_WAVE
    const PART_20MMGUN
    const PART_36MMGUN
    const PART_46MMGUN
    const PART_HEDGE_B
    const PART_BATGUN
    const PART_SEABOMB
    const PART_SUPRGUN
    const PART_ROLLER
    const PART_BIGROLR
    const PART_STINGER
    const PART_CAT
    const PART_HELLCAT
    const PART_M_GUN
    const PART_LAUNCHR
    const PART_CANNON
    const PART_BAZOOKA
    const PART_MINE
    const PART_AUTOGUN
    const PART_RCKT_L
    const PART_MISSILE
    const PART_SPIKTIR
    const PART_BIGFOOT
    const PART_FIREBOMB
    const PART_TOSS_B
