	const_def

	const SONG_NONE
	const SONG_TITLE ; SONG_BISCO
	const SONG_CREDITS
	const SONG_TOWN1
	const SONG_WILD_BATTLE
	const SONG_VICTORY
	const SONG_TRAINER_BATTLE
	const SONG_TOWN2
	const SONG_CAVE
	const SONG_TOWER
	const SONG_0A
	const SONG_SHOP
	const SONG_CENTER
	const SONG_MAZE_MINIGAME
	const SONG_JUMP_MINIGAME
	const SONG_CARD_MINIGAME
	const SONG_PUNCH_MINIGAME
	const SONG_TOWN3
	const SONG_TEIL_TOWN
	const SONG_PRINCE_TEIL
	const SONG_WORLD_MAP
	const SONG_GYM_LEADER_BATTLE
	const SONG_HEAL
	const SONG_LEVEL_UP
	const SONG_ENCOUNTER_BEAUTY
	const SONG_ENCOUNTER_UNKNOWN
	const SONG_ENCOUNTER_EVIL
