
	char_def $a6

	defchar "を", "ヲ"
	defchar "ぁ", "ァ"
	defchar "ぃ", "ィ"
	defchar "ぅ", "ゥ"
	defchar "ぇ", "ェ"
	defchar "ぉ", "ォ"
	defchar "ゃ", "ャ"
	defchar "ゅ", "ュ"
	defchar "ょ", "ョ"
	defchar "っ", "ッ"
	defchar "ー" ; b0
	defchar "あ", "ア"
	defchar "い", "イ"
	defchar "う", "ウ"
	defchar "え", "エ"
	defchar "お", "オ"
	defchar "か", "カ"
	defchar "き", "キ"
	defchar "く" , "ク"
	defchar "け", "ケ"
	defchar "こ", "コ"
	defchar "さ", "サ"
	defchar "し", "シ"
	defchar "す", "ス"
	defchar "せ", "セ"
	defchar "そ", "ソ"
	defchar "た", "タ" ; c0
	defchar "ち", "チ"
	defchar "つ", "ツ"
	defchar "て", "テ"
	defchar "と", "ト"
	defchar "な", "ナ"
	defchar "に", "ニ"
	defchar "ぬ", "ヌ"
	defchar "ね", "ネ"
	defchar "の", "ノ"
	defchar "は", "ハ"
	defchar "ひ", "ヒ"
	defchar "ふ", "フ"
	defchar "へ", "ヘ"
	defchar "ほ", "ホ"
	defchar "ま", "マ"
	defchar "み", "ミ" ; d0
	defchar "む", "ム"
	defchar "め", "メ"
	defchar "も", "モ"
	defchar "や", "ヤ"
	defchar "ゆ", "ユ"
	defchar "よ", "ヨ"
	defchar "ら", "ラ"
	defchar "り", "リ"
	defchar "る", "ル"
	defchar "れ", "レ"
	defchar "ろ", "ロ"
	defchar "わ", "ワ"
	defchar "ん", "ン"
	defchar "ﾞ"
	defchar "ﾟ" ; df
