
	char_def $a6

	defchar "を", "ヲ"
	defchar "ぁ", "ァ"
	defchar "ぃ", "ィ"
	defchar "ぅ", "ゥ"
	defchar "ぇ", "ェ"
	defchar "ぉ", "ォ"
	defchar "ゃ", "ャ"
	defchar "ゅ", "ュ"
	defchar "ょ", "ョ"
	defchar "っ", "ッ"
	defchar "ー" ; b0
	defchar "あ", "ア"
	defchar "い", "イ"
	defchar "う", "ウ"
	defchar "え", "エ"
	defchar "お", "オ"
	defchar "か", "カ"
	defchar "き", "キ"
	defchar "く" , "ク"
	defchar "け", "ケ"
	defchar "こ", "コ"
	defchar "さ", "サ"
	defchar "し", "シ"
	defchar "す", "ス"
	defchar "せ", "セ"
	defchar "そ", "ソ"
	defchar "た", "タ" ; c0
	defchar "ち", "チ"
	defchar "つ", "ツ"
	defchar "て", "テ"
	defchar "と", "ト"
	defchar "な", "ナ"
	defchar "に", "ニ"
	defchar "ぬ", "ヌ"
	defchar "ね", "ネ"
	defchar "の", "ノ"
	defchar "は", "ハ"
	defchar "ひ", "ヒ"
	defchar "ふ", "フ"
	defchar "へ", "ヘ"
	defchar "ほ", "ホ"
	defchar "ま", "マ"
	defchar "み", "ミ" ; d0
	defchar "む", "ム"
	defchar "め", "メ"
	defchar "も", "モ"
	defchar "や", "ヤ"
	defchar "ゆ", "ユ"
	defchar "よ", "ヨ"
	defchar "ら", "ラ"
	defchar "り", "リ"
	defchar "る", "ル"
	defchar "れ", "レ"
	defchar "ろ", "ロ"
	defchar "わ", "ワ"
	defchar "ん", "ン"
	defchar "ﾞ"
	defchar "ﾟ" ; df

    char_def $20
    defchar " "
    defchar "!"
    defchar "\""
    defchar "#"
    defchar "$"
    defchar "%"
    defchar "&"
    defchar "'"
    defchar "("
    defchar ")"
    defchar "*"
    defchar "+"
    defchar ","
    defchar "-"
    defchar "."
    defchar "/"

    defchar "0"
    defchar "1"
    defchar "2"
    defchar "3"
    defchar "4"
    defchar "5"
    defchar "6"
    defchar "7"
    defchar "8"
    defchar "9"
    defchar ":"
    defchar ";"
    defchar "<"
    defchar "="
    defchar ">"
    defchar "?"

    defchar "@"
    defchar "A"
    defchar "B"
    defchar "C"
    defchar "D"
    defchar "E"
    defchar "F"
    defchar "G"
    defchar "H"
    defchar "I"
    defchar "J"
    defchar "K"
    defchar "L"
    defchar "M"
    defchar "N"
    defchar "O"

    defchar "P"
    defchar "Q"
    defchar "R"
    defchar "S"
    defchar "T"
    defchar "U"
    defchar "V"
    defchar "W"
    defchar "X"
    defchar "Y"
    defchar "Z"
    defchar "["
    defchar "\\"
    defchar "]"
    defchar "^"
    defchar "_"

    defchar "`"
    defchar "a"
    defchar "b"
    defchar "c"
    defchar "d"
    defchar "e"
    defchar "f"
    defchar "g"
    defchar "h"
    defchar "i"
    defchar "j"
    defchar "k"
    defchar "l"
    defchar "m"
    defchar "n"
    defchar "o"

    defchar "p"
    defchar "q"
    defchar "r"
    defchar "s"
    defchar "t"
    defchar "u"
    defchar "v"
    defchar "w"
    defchar "x"
    defchar "y"
    defchar "z"
    defchar "\{"
    defchar "|"
    defchar "\}"
    defchar "~"
