INCLUDE "constants/misc_constants.asm"
INCLUDE "constants/time_constants.asm"
INCLUDE "constants/predef_constants.asm"
INCLUDE "constants/robot_constants.asm"
INCLUDE "constants/song_constants.asm"
INCLUDE "constants/map_dimension_constants.asm"
INCLUDE "constants/item_constants.asm"
