INCLUDE "includes.asm"
INCLUDE "charmap.asm"
INCLUDE "macros/bank20.asm"

SECTION "Bank 2a", ROMX
	script_library 2a

INCLUDE "maps/scripts/unknown_a922b.asm"
INCLUDE "maps/scripts/unknown_a973e.asm"
INCLUDE "maps/scripts/unknown_a97f3.asm"
INCLUDE "maps/scripts/unknown_a98a2.asm"
INCLUDE "maps/scripts/unknown_a9957.asm"
INCLUDE "maps/scripts/unknown_a9a0c.asm"
INCLUDE "maps/scripts/unknown_a9ac1.asm"
INCLUDE "maps/scripts/unknown_a9b7b.asm"
INCLUDE "maps/scripts/unknown_a9c3d.asm"
INCLUDE "maps/scripts/unknown_a9cfa.asm"
INCLUDE "maps/scripts/unknown_a9db4.asm"
INCLUDE "maps/scripts/unknown_a9e71.asm"
INCLUDE "maps/scripts/unknown_a9f2b.asm"
INCLUDE "maps/scripts/unknown_aa083.asm"
INCLUDE "maps/scripts/unknown_aa218.asm"
INCLUDE "maps/scripts/unknown_aa5cb.asm"
INCLUDE "maps/scripts/unknown_aac19.asm"
INCLUDE "maps/scripts/unknown_aaed3.asm"
INCLUDE "maps/scripts/unknown_ab199.asm"
INCLUDE "maps/scripts/unknown_ab46b.asm"
INCLUDE "maps/scripts/unknown_ab7cc.asm"
INCLUDE "maps/scripts/unknown_abf90.asm"
