#!/usr/bin/env python

import argparse
import atexit
import dataclasses
import hashlib
import logging
import pathlib
import re
import subprocess
import sys
import warnings
from collections.abc import Callable
from functools import cached_property
from typing import Literal, SupportsIndex, get_args

logging.basicConfig(
    format="[%(asctime)s] %(name)s: %(levelname)s: %(message)s", level=logging.INFO
)
log = logging.getLogger("unidasm")

SymbolsDict = dict[str, dict[tuple[int, int], str]]
SupportedROMsLiteral = Literal["sun", "star", "sun-en"]
SUPPORTED_ROMS = get_args(SupportedROMsLiteral)


my_file = pathlib.Path(__file__)
ROOT_DIR = my_file.parent.parent


# Suppress stacktrace in warnings
# Generated by Google Gemini in search, and edited for correctness
def custom_formatwarning(message, category, filename, lineno, line=None):
    return "%s:%s: %s: %s\n" % (filename, lineno, category.__name__, message)


warnings.formatwarning = custom_formatwarning


REGION_LIMITS = {
    "ROM": 0x8000,
    "VRAM": 0xA000,
    "SRAM": 0xC000,
    "WRAM": 0xE000,
    "ERAM": 0xFF00,
    "HRAM": 0x10000,
}


@dataclasses.dataclass
class Instruction:
    addr_operand = {
        0x01: 1,  # ld bc, n16
        0x08: 0,  # ld [a16], sp
        0x11: 1,  # ld de, n16
        0x18: 0,  # jr r8
        0x20: 1,  # jr nz, r8
        0x21: 1,  # ld hl, n16
        0x28: 1,  # jr z, r8
        0x30: 1,  # jr nc, r8
        0x31: 1,  # ld sp, n16
        0x38: 1,  # jr c, r8
        0xC2: 1,  # jp nz, a16
        0xC3: 0,  # jp a16
        0xC4: 1,  # call nz, a16
        0xCA: 1,  # jp z, a16
        0xCC: 1,  # call z, a16
        0xCD: 0,  # call a16
        0xD2: 1,  # jp nc, a16
        0xD4: 1,  # call nc, a16
        0xDA: 1,  # jp c, a16
        0xDC: 1,  # call c, a16
        0xE0: 0,  # ldh [a8], a
        0xEA: 0,  # ld [a16], a
        0xF0: 1,  # ldh a, [a8]
        0xFA: 1,  # ld a, [a16]
    }

    offset: int
    raw: bytearray
    mnemonic: str
    operands: list[str]
    verbose: bool = dataclasses.field(default=True)
    label: str | None = dataclasses.field(default=None)
    comment: str = dataclasses.field(default="")

    def __str__(self):
        if self.operands:
            operands = ", ".join(self.operands)
            insn = f"{self.mnemonic} {operands}"
        else:
            insn = self.mnemonic
        label = f"{self.label}:\n" if self.label else ""
        comment = ""
        if self.verbose:
            bank, addr = rom_offset_to_addr(self.offset)
            raw = " ".join(f"{x:02X}" for x in self.raw)
            comment += f" ; {self.offset:05X} ({bank:02x}:{addr:04x}) -> {raw}"
        if self.comment:
            comment += f" ; {self.comment}"
        return f"{label}\t{insn}{comment}"

    def __getitem__(self, index: SupportsIndex) -> str:
        return self.operands[index]

    def has_addr_operand(self):
        return self.raw[0] in Instruction.addr_operand

    def has_addr_macro(self):
        return self.mnemonic in {"read_hl_from", "write_hl_to"}

    def has_nonaddr_macro(self):
        return self.mnemonic in {"read_hl_from_sp_plus", "write_hl_to_sp_plus"}

    def get_addr_operand(self):
        if self.has_addr_macro():
            return rgbds_str_to_int(self[0].strip("[]"))
        if self.has_nonaddr_macro():
            return None
        if (oper_i := Instruction.addr_operand.get(self.raw[0])) is not None:
            return rgbds_str_to_int(self[oper_i].strip("[]"))

    def __len__(self):
        return len(self.raw)


def rgbds_str_to_int(x: str):
    if x.startswith("$"):
        return int(x[1:], 16)
    else:  # assume base 10
        return int(x)


def get_region(addr: int) -> str | None:
    region = None
    if addr >= 0 and addr < 0x10000:
        for region, upper in REGION_LIMITS.items():
            if addr < upper:
                break
    return region


def parse_gbhw_asm(asmfile: pathlib.Path) -> dict[int, str]:
    pattern = re.compile(r"^DEF +(\w+) +EQU +\$(ff[0-9a-f][0-9a-f])", re.IGNORECASE)
    ret: dict[int, str] = {}
    with asmfile.open() as fp:
        for line in fp:
            if m := pattern.match(line):
                name, addr = m.groups()
                ret[int(addr, 16)] = name
    return ret


def addr_to_rom_offset(bank: int, addr: int) -> int:
    if addr >= 0x8000:
        raise ValueError("not a ROM address")
    return (bank << 14) | (addr & 0x3FFF)


def rom_offset_to_addr(offset: int) -> tuple[int, int]:
    bank = offset >> 14
    addr = offset & 0x3FFF
    if bank != 0:
        addr |= 0x4000
    return bank, addr


def sanitize_operand(operand: str):
    return (
        operand.lower()
        .replace("(", "[")
        .replace(")", "]")
        .replace("hl+", "hli")
        .replace("hl-", "hld")
    )


class Macro:
    def __init_subclass__(cls):
        pass

    def __call__(self, instructions: list[Instruction], symbols: SymbolsDict):
        pass


def any_int(arg: str):
    return int(arg, 0)


class Namespace(argparse.Namespace):
    version: SupportedROMsLiteral
    start: int
    end: int
    _unidasm: pathlib.Path = ROOT_DIR / "tools" / "unidasm"
    outfile: pathlib.Path = None
    no_comments: bool = False
    no_trim: bool = False

    @classmethod
    def from_cli(cls, args: list[str] | None = None):
        parser = argparse.ArgumentParser()
        parser.add_argument(
            "version",
            choices=SUPPORTED_ROMS,
            help="ROM version, used to find the baserom and symtab",
        )
        parser.add_argument(
            "start", type=any_int, help="Start offset in the flat ROM image, inclusive"
        )
        parser.add_argument(
            "end", type=any_int, help="End offset in the flat ROM image, exclusive"
        )
        parser.add_argument(
            "-o", "--outfile", type=pathlib.Path, help="Output file path"
        )
        parser.add_argument(
            "--unidasm",
            dest="_unidasm",
            type=pathlib.Path,
            help="Path to the unidasm executable",
        )
        parser.add_argument(
            "-q",
            dest="no_comments",
            action="store_true",
            help="Suppress address and raw bytes comments",
        )
        parser.add_argument(
            "-T",
            "--no-trim",
            dest="no_trim",
            action="store_true",
            help="Suppress trimming past the first absolute ret instruction",
        )
        return parser.parse_args(args, cls())

    @property
    def target_md5(self):
        checksums = ROOT_DIR / f"{self.version}.md5"
        with checksums.open() as md5file:
            for line in md5file:
                target, path = line.rstrip("\n").split(None, 1)
                if path.lstrip("*") == f"robo{self.version}.gbc":
                    break
            else:
                raise ValueError(
                    f"unable to find MD5 digest for robo{self.version}.gbc"
                )
        return target

    @cached_property
    def unidasm(self):
        if not self._unidasm.exists():
            raise FileNotFoundError(self._unidasm)
        return self._unidasm

    @cached_property
    def baserom(self):
        for romname in (f"robo{self.version}.gbc", f"baserom-{self.version}.gbc"):
            baserom = ROOT_DIR / romname
            if not baserom.exists():
                continue
            if check_md5sum(baserom, self.target_md5):
                break
        else:
            raise ValueError(
                f"unable to find a suitable copy of Robopon {self.version.title()} version"
            )
        return baserom

    @cached_property
    def symfile(self):
        symfile = ROOT_DIR / f"robo{self.version}.sym"
        if not symfile.exists():
            raise FileNotFoundError("please run `make` before running this script")
        return symfile

    @cached_property
    def symbols(self) -> SymbolsDict:
        addr_to_symbol = {region: {} for region in REGION_LIMITS}
        with self.symfile.open() as fp:
            for line in fp:
                if line.startswith(";"):
                    continue
                bank, addr, name = re.split("[ :]", line.rstrip("\n"))
                if "." in name:
                    continue
                bank = int(bank, 16)
                addr = int(addr, 16)
                region = get_region(addr)
                addr_to_symbol[region][(bank, addr)] = name
        # Augment with MMIO registers
        addr_to_symbol["HRAM"] |= parse_gbhw_asm(ROOT_DIR / "gbhw.asm")
        return addr_to_symbol

    def disassemble(self, start: int | None = None, end: int | None = None, /):
        """
        Produce a raw disassembly of the baserom image between the given flat ROM addresses.
        """
        if start is None:
            start = self.start
        if end is None:
            end = self.end
        if self.end <= self.start:
            raise ValueError("end must be strictly greater than start")
        args = [
            str(self.unidasm.absolute()),
            str(self.baserom.absolute()),
            "-skip",
            hex(start),
            "-count",
            hex(end - start),
            "-basepc",
            hex(start),
            "-arch",
            "lr35902",
        ]
        proc = subprocess.run(
            args, capture_output=True, check=True, text=True, timeout=10
        )
        result: list[Instruction] = []
        for line in proc.stdout.splitlines():
            offset, rest = line.split(": ", 1)
            raw = bytearray(int(x, 16) for x in rest[:10].strip().split())
            mnemonic = rest[10:15].strip()
            if mnemonic == "ld" and (raw[0] & 0xEF) == 0xE0:
                mnemonic = "ldh"
            operands = [sanitize_operand(op) for op in rest[15:].strip().split(",")]
            result.append(
                Instruction(
                    int(offset, 16),
                    raw,
                    mnemonic,
                    operands,
                    verbose=not self.no_comments,
                )
            )
        return result

    def redisassemble(
        self, instructions: list[Instruction], index: int, start: int, chomp: int
    ):
        with self.baserom.open("rb") as romfile:
            romfile.seek(start)
            value = int.from_bytes(romfile.read(chomp), "little")
        end = instructions[-1].offset + len(instructions[-1])
        if end > start + chomp:
            new_instructions = self.disassemble(start + chomp, end)
            old_index = index
            new_index = 0
            while instructions[index].offset != new_instructions[new_index].offset:
                if instructions[index].offset < new_instructions[new_index].offset:
                    index += 1
                else:
                    new_index += 1

            del instructions[old_index:index]
            for new_insn in new_instructions[:new_index][::-1]:
                instructions.insert(old_index, new_insn)
        else:
            del instructions[index:]
        return value

    def handle_stack_macros(self, instructions: list[Instruction]):
        # we will be modifying instructions in-place, so can't iterate over it pythonically
        i = -1
        while (i := i + 1) < len(instructions):
            insn = instructions[i]
            if not insn.mnemonic.startswith("call"):
                continue
            operand = insn.get_addr_operand()
            if not (0x4000 > operand >= 0):  # ROM0
                continue
            if (symbol := self.symbols["ROM"].get((0, operand))) is None:
                continue
            chomp_map = {
                "GetHLAtSPPlusParam8": ("read_hl_from_sp_plus", 1),
                "GetHLAtSPPlusParam16": ("read_hl_from_sp_plus", 2),
                "WriteHLToSPPlusParam8": ("write_hl_to_sp_plus", 1),
                "WriteHLToSPPlusParam16": ("write_hl_to_sp_plus", 2),
                "ReadHalfWordAt": ("read_hl_from", 2),
                "WriteHalfWordTo": ("write_hl_to", 2),
            }
            macro, chomp = chomp_map.get(symbol, (None, None))
            if macro is None:
                continue
            value = self.redisassemble(
                instructions,
                i + 1,
                insn.offset + 3,
                chomp,
            )
            insn.mnemonic = macro
            insn.operands = [f"${{:0{chomp}x}}".format(value)]
            insn.raw += value.to_bytes(chomp, "little")

    def trim_to_ret(self, instructions: list[Instruction]):
        if self.no_trim:
            return
        for i, insn in enumerate(instructions):
            if insn.mnemonic == "ret" and len(insn) == 1:
                if i != len(instructions) - 1:
                    warnings.warn(f"Encountered ret at ${insn.offset:x}, truncating")
                    del instructions[i + 1 :]
                break
        else:
            warnings.warn(f"Reached ${insn.offset + len(insn.raw)} without a ret")

    def apply_symtab(self, instructions: list[Instruction]):
        # 2-pass operation
        # first pass: find all addresses and update the symbols dict
        # second pass: insert labels into the instructions list
        for insn in instructions:
            bank, _ = rom_offset_to_addr(insn.offset)
            if (addr_operand := insn.get_addr_operand()) is not None:
                if insn.mnemonic.startswith("jr"):
                    addr_operand &= 0x3FFF
                    if bank != 0:
                        addr_operand |= 0x4000
                elif insn.mnemonic == "ldh":
                    region = "HRAM"
                    addr_operand |= 0xFF00
                else:
                    region = get_region(addr_operand)
                if region is None:
                    continue
                if region == "ROM":
                    op_bank = 0 if addr_operand < 0x4000 else bank
                else:
                    op_bank = 0
                if (op_bank, addr_operand) not in self.symbols[region]:
                    if region == "ROM":
                        # ld r16, n16 --> suppress unlikely targets
                        if (
                            insn.raw[0] in (0x01, 0x11, 0x21, 0x31)
                            and addr_operand <= 0x800
                        ):
                            continue
                        op_offset = addr_to_rom_offset(op_bank, addr_operand)
                        name = f"label_{op_offset:04x}"
                    else:
                        name = f"{region[0].lower()}{addr_operand:04x}"
                    self.symbols[region][(op_bank, addr_operand)] = name
                    log.info(
                        "soft adding symbol %s at %02x:%04x",
                        name,
                        op_bank,
                        addr_operand,
                    )
                else:
                    name = self.symbols[region][(op_bank, addr_operand)]
                oper_i = Instruction.addr_operand[insn.raw[0]]
                insn.operands[oper_i] = (
                    f"[{name}]" if "[" in insn.operands[oper_i] else name
                )
        for insn in instructions:
            bank, addr = rom_offset_to_addr(insn.offset)
            if (bank, addr) in self.symbols["ROM"]:
                label = self.symbols["ROM"][(bank, addr)]
                if "." in label:
                    label = "." + label.rsplit(".", 1)[-1]
                insn.label = label

    def handle_mulhl_macro(
        self, instructions: list[Instruction], index: int
    ) -> tuple[int, int, str] | None:
        if instructions[index].raw != b"\x29":  # add hl, hl
            return
        end = index
        multiplicand = 0
        de_pos = None
        bc_pos = None
        hl_pos = 0
        # Look earlier for `ld e, l / ld d, h`
        if (
            index >= 2
            and instructions[index - 2].raw == b"\x5d"
            and instructions[index - 1].raw == b"\x54"
        ):
            end = index = index - 2
        # Scan forward for the end
        while True:
            if instructions[end].raw in (b"\x09", b"\x19", b"\x29"):
                # add hl, bc | add hl, de | add hl, hl
                if instructions[end].raw == b"\x29":
                    hl_pos += 1
                end += 1
            elif (
                instructions[end].raw == b"\x5d"
                and instructions[end + 1].raw == b"\x54"
                and de_pos is None
                and bc_pos is None
            ):
                # ld e, l / ld d, h
                de_pos = hl_pos
                end += 2
            elif (
                instructions[end].raw == b"\x4d"
                and instructions[end + 1].raw == b"\x44"
                and bc_pos is None
            ):
                # ld c, l / ld b, h
                bc_pos = hl_pos
                end += 2
            else:
                break
        multiplicand = 2**hl_pos
        if de_pos is not None:
            multiplicand += 2**de_pos
        if bc_pos is not None:
            multiplicand += 2**bc_pos
        if multiplicand >= 3:  # use for 3x or more
            return index, end, str(multiplicand)

    def is_regswap_de_hl_macro(self, instructions: list[Instruction], index: int):
        # push de | push hl | pop de | pop hl
        if (
            instructions[index].raw == b"\xd5"
            and instructions[index + 1].raw == b"\xe5"
            and instructions[index + 2].raw == b"\xd1"
            and instructions[index + 3].raw == b"\xe1"
        ):
            return index, index + 4

    def is_set_farcall_addrs_hli_macro(
        self, instructions: list[Instruction], index: int
    ):
        if (
            instructions[index].mnemonic == "ld"
            and instructions[index].operands == ["hl", "wFarCallDestBank"]
            and instructions[index + 1].mnemonic == "ld"
            and instructions[index + 1].operands[0] == "[hl]"
            and instructions[index + 2].mnemonic == "inc"
            and instructions[index + 2].operands[0] == "hl"
            and instructions[index + 3].mnemonic == "ld"
            and instructions[index + 3].operands[0] == "[hl]"
            and instructions[index + 4].mnemonic == "inc"
            and instructions[index + 4].operands[0] == "hl"
            and instructions[index + 5].mnemonic == "ld"
            and instructions[index + 5].operands[0] == "[hl]"
        ):
            bank = rgbds_str_to_int(instructions[index + 1].operands[1])
            addr = (
                rgbds_str_to_int(instructions[index + 5].operands[1]) << 8
            ) | rgbds_str_to_int(instructions[index + 3].operands[1])
            if (bank, addr) not in self.symbols["ROM"]:
                op_offset = addr_to_rom_offset(bank, addr)
                name = f"Func_{op_offset:x}"
                self.symbols["ROM"][(bank, addr)] = name
                log.info(
                    "soft adding symbol %s at %02x:%04x",
                    name,
                    bank,
                    addr,
                )
            else:
                name = self.symbols["ROM"][(bank, addr)]
            return index, index + 6, name

    combining_macros: dict[
        str, Callable[["Namespace", list[Instruction], int], tuple[int, int, str]]
    ] = {
        "mulhl": handle_mulhl_macro,
        "swap_de_hl": is_regswap_de_hl_macro,
        "set_farcall_addrs_hli": is_set_farcall_addrs_hli_macro,
    }

    def handle_combining_macros(self, instructions: list[Instruction]):
        """Function to combine multiple well-formed instructions into one"""
        # we will be modifying instructions in-place, so can't iterate over it pythonically
        i = -1
        while (i := i + 1) < len(instructions):
            for mnemonic, func in self.combining_macros.items():
                if result := func(self, instructions, i):
                    new_i, end, *operands = result
                    old_instructions = instructions[new_i:end]
                    new_instruction = Instruction(
                        offset=old_instructions[0].offset,
                        mnemonic=mnemonic,
                        operands=operands,
                        raw=b"".join(insn.raw for insn in old_instructions),
                        verbose=old_instructions[0].verbose,
                        label=old_instructions[0].label,
                    )
                    del instructions[new_i:end]
                    instructions.insert(
                        new_i,
                        new_instruction,
                    )
                    i = new_i
                    break

    def dumps(self, instructions: list[Instruction]):
        return "\n".join(str(insn) for insn in instructions)

    def dump(self, instructions: list[Instruction]):
        if self.outfile is None:
            outfile = sys.stdout
        else:
            outfile = self.outfile.open("w")
            atexit.register(outfile.close)
        for insn in instructions:
            print(insn, file=outfile)


def check_md5sum(rom: pathlib.Path, target: str):
    with rom.open("rb") as fp:
        hasher = hashlib.md5(fp.read())
    checksum = "".join(f"{x:02x}" for x in hasher.digest())
    return checksum == target


def main():
    args = Namespace.from_cli()
    instructions = args.disassemble()
    args.handle_stack_macros(instructions)
    args.trim_to_ret(instructions)
    args.apply_symtab(instructions)
    args.handle_combining_macros(instructions)
    args.dump(instructions)


if __name__ == "__main__":
    main()
